#!usr/bin/env python3

import sys

def taxcal(**kw):
 
    for key, value in kw.items():
        base = value - value * (0.08 + 0.02 + 0.005 + 0.06) - 3500
        if base < 0:
            tax = 0
            get = base + 3500
        else:
            if base <= 1500:
                tax = base * 0.03
            elif base <= 4500:
                tax = base * 0.1 - 105
            elif base <= 9000:
                tax = base * 0.2 - 555
            elif base <= 35000:
                tax = base * 0.25 - 1005
            elif base <= 55000:
                tax = base * 0.3 - 2755
            elif base <= 80000:
                tax = base * 0.35 - 5505        
            else:
                tax = base * 0.45 - 13505
        get = base - tax + 3500
 
        print('{0:}:{1:.2f}'.format(key, get))


if __name__ == '__main__':
    
    money_dic = {}

    for arg in sys.argv[1:]:
        no, money = arg.split(':')
        try:
            a = int(no)
            b = int(money)
        except:
            print("Parameter Error")
        money_dic[no] = b
    
    taxcal(**money_dic)
