#!/usr/bin/env python3

import sys

try:
    salary = int(sys.argv[1])
    taxbase = salary - 0 - 3500

    if taxbase <= 0:
        tax = 0 
    elif 0 < taxbase <= 1500:
        tax = taxbase * 0.03 - 0
    elif 1500 < taxbase <= 4500:
        tax = taxbase * 0.10 - 105
    elif 4500 < taxbase <= 9000:
        tax = taxbase * 0.20 - 555
    elif 9000 < taxbase <= 35000:
        tax = taxbase * 0.25 - 1005
    elif 35000 < taxbase <= 55000:
        tax = taxbase * 0.30 - 2755
    elif 55000 < taxbase <= 80000:
        tax = taxbase * 0.35 - 5505
    else:
        tax = taxbase * 0.45 - 13505

    print(format(tax, ".2f"))

except ValueError:
    print('Parameter Error')
